package com.freelancer.entity.enums;

public enum NotificationType {
    NEW_APPLICATION, APPLICATION_ACCEPTED, PAYMENT_RECEIVED, PROGRESS_REPORT,
    COMPLETION_SUBMITTED, JOB_COMPLETED, PAYOUT_COMPLETED, NEW_MESSAGE, SYSTEM
}
